In [ ]:
"""Goal: filter for 2025, all, oral + spotlight and send in csv"""

In [1]:
import pandas as pd
df = pd.read_json("institution_venues_v14.json")

In [1]:
import pandas as pd
df = pd.read_csv("lala_v10.csv")

In [7]:
df[df.institution=='Meta'].country.value_counts()

country
US    81
GB    14
FR     8
CA     5
CH     1
IT     1
SG     1
Name: count, dtype: int64

In [8]:
df[df.institution=='Google'].country.value_counts()

country
US    185
CH     20
GB     11
CA      9
IL      8
FR      5
DE      3
AU      3
KR      2
IN      2
AT      1
TH      1
BR      1
PL      1
CN      1
Name: count, dtype: int64

In [6]:
df[df.institution=='Microsoft'].country.value_counts()

country
US    82
CN    57
GB     9
CA     6
IN     4
SE     3
CH     3
DE     2
MX     1
NO     1
SG     1
IL     1
Name: count, dtype: int64

In [3]:
keys = sorted({k for d in df["venues"].dropna() for k in d.keys()})
keys

['NeurIPS 2025 Datasets and Benchmarks Track oral',
 'NeurIPS 2025 Datasets and Benchmarks Track poster',
 'NeurIPS 2025 Datasets and Benchmarks Track spotlight',
 'NeurIPS 2025 Position Paper Track',
 'NeurIPS 2025 Position Paper Track Oral',
 'NeurIPS 2025 oral',
 'NeurIPS 2025 poster',
 'NeurIPS 2025 spotlight']

In [ ]:
keys = [
    "NeurIPS 2025 Datasets and Benchmarks Track oral",
    "NeurIPS 2025 Datasets and Benchmarks Track spotlight",
    "NeurIPS 2025 spotlight",
    "NeurIPS 2025 oral",
]

filtered = (
    df["venues"]
      .apply(lambda d: {k: d.get(k) for k in keys} if isinstance(d, dict) else {})
)

out = df.join(pd.DataFrame(filtered.tolist(), index=df.index)).fillna({k: 0 for k in keys})

In [21]:
out[['name','parent','urban_zone','country','parent2']+keys].rename(columns={"parent": "area", "parent2": "region"}).to_csv("neurips_spotlight_oral_2025.csv",index=0)

In [16]:
out

,name,parent,color,urban_zone,country,parent2,urban_id,name2,venues,NeurIPS 2025 Datasets and Benchmarks Track oral,NeurIPS 2025 Datasets and Benchmarks Track spotlight,NeurIPS 2025 spotlight,NeurIPS 2025 oral
0,01.AI,China,#126782,Beijing,CN,North China,204.0,01.AI,{'NeurIPS 2025 Datasets and Benchmarks Track p...,0.0,0.0,0.0,0.0
1,108 Hospital,Rest of the world,#D81159,Hanoi,VN,Red River Delta,1840.0,108 Hospital,{'NeurIPS 2025 Datasets and Benchmarks Track p...,0.0,0.0,0.0,0.0
2,1X,US,#FFBC42,None,US,None,NaN,1X,{'NeurIPS 2025 poster': 1},0.0,0.0,0.0,0.0
3,2077AI,Rest of the world,#D81159,Singapore,SG,Central Region,1490.0,2077AI,{'NeurIPS 2025 Datasets and Benchmarks Track p...,0.0,0.0,0.0,0.0
4,23andMe,US,#FFBC42,San Jose,US,Pacific Coast,1786.0,23andMe,{'NeurIPS 2025 poster': 1},0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1924,École de technologie supérieure,Rest of the world,#D81159,Montreal,CA,Quebec,167.0,École de technologie supérieure,{'NeurIPS 2025 Datasets and Benchmarks Track s...,0.0,1.0,0.0,0.0
1925,École Polytechnique,Europe,#43df58,Paris,FR,Ile-de-France,715.0,École Polytechnique,"{'NeurIPS 2025 oral': 1, 'NeurIPS 2025 poster'...",0.0,0.0,3.0,1.0
1926,Örebro University,Europe,#43df58,Stockholm,SE,Stockholm County,1538.0,Örebro University,{'NeurIPS 2025 Datasets and Benchmarks Track p...,0.0,0.0,0.0,0.0
1927,Minzu University of China,China,#126782,Beijing,CN,North China,204.0,Minzu University of China,{'NeurIPS 2025 Datasets and Benchmarks Track p...,0.0,0.0,0.0,0.0
1928,言创智信,China,#126782,Beijing,CN,North China,204.0,言创智信,{'NeurIPS 2025 poster': 2},0.0,0.0,0.0,0.0

In [13]:
out[out.name=='Stanford']

,name,parent,color,urban_zone,country,parent2,urban_id,name2,venues,NeurIPS 2025 Datasets and Benchmarks Track oral,NeurIPS 2025 Datasets and Benchmarks Track spotlight,NeurIPS 2025 spotlight,NeurIPS 2025 oral
1397,Stanford,US,#FFBC42,San Jose,US,Pacific Coast,1786.0,Stanford,{'NeurIPS 2025 Datasets and Benchmarks Track o...,1.0,6.0,28.0,5.0

In [12]:
df

,name,parent,color,urban_zone,country,parent2,urban_id,name2,venues
0,01.AI,China,#126782,Beijing,CN,North China,204.0,01.AI,{'NeurIPS 2025 Datasets and Benchmarks Track p...
1,108 Hospital,Rest of the world,#D81159,Hanoi,VN,Red River Delta,1840.0,108 Hospital,{'NeurIPS 2025 Datasets and Benchmarks Track p...
2,1X,US,#FFBC42,None,US,None,NaN,1X,{'NeurIPS 2025 poster': 1}
3,2077AI,Rest of the world,#D81159,Singapore,SG,Central Region,1490.0,2077AI,{'NeurIPS 2025 Datasets and Benchmarks Track p...
4,23andMe,US,#FFBC42,San Jose,US,Pacific Coast,1786.0,23andMe,{'NeurIPS 2025 poster': 1}
...,...,...,...,...,...,...,...,...,...
1924,École de technologie supérieure,Rest of the world,#D81159,Montreal,CA,Quebec,167.0,École de technologie supérieure,{'NeurIPS 2025 Datasets and Benchmarks Track s...
1925,École Polytechnique,Europe,#43df58,Paris,FR,Ile-de-France,715.0,École Polytechnique,"{'NeurIPS 2025 oral': 1, 'NeurIPS 2025 poster'..."
1926,Örebro University,Europe,#43df58,Stockholm,SE,Stockholm County,1538.0,Örebro University,{'NeurIPS 2025 Datasets and Benchmarks Track p...
1927,Minzu University of China,China,#126782,Beijing,CN,North China,204.0,Minzu University of China,{'NeurIPS 2025 Datasets and Benchmarks Track p...
1928,言创智信,China,#126782,Beijing,CN,North China,204.0,言创智信,{'NeurIPS 2025 poster': 2}

In [20]:
import pandas as pd
test = pd.read_csv('/Users/robertpraas/CEPS-DST Dropbox/Robert Praas/1-load/org/urban/ai/crunchbase/2025.csv')

In [24]:
test[test.geo=='Herat (NA)'].sort_values(by='count',ascending=0).head(10).org.to_list()

['Lovable',
 'Centre de Collaboration MiQro Innovation',
 'Black Forest Labs',
 'Multiverse Computing',
 'Harrison.ai',
 'CuspAI',
 'Luminance',
 'Feedzai',
 'Artera',
 'Ultromics']

In [10]:
import pandas as pd
df = pd.read_csv('/Users/robertpraas/CEPS-DST Dropbox/Robert Praas/1-load/org/urban/ai/crunchbase/2022.csv')

In [11]:
df[df.geo=='Herat (NA)'].sort_values(by='count',ascending=0)

                      org         geo                   domain        count
1254  Digital Diagnostics  Herat (NA)  Artificial Intelligence  121266488.0
2114               Invoca  Herat (NA)  Artificial Intelligence   83000000.0
1061    Customcells Group  Herat (NA)  Artificial Intelligence   63334498.0
3879         Speechmatics  Herat (NA)  Artificial Intelligence   61303485.0
2639               ModMed  Herat (NA)  Artificial Intelligence   53369486.0
...                   ...         ...                      ...          ...
1399              Elythea  Herat (NA)  Artificial Intelligence      15000.0
4231               Trigan  Herat (NA)  Artificial Intelligence      11338.0
3174           Pmf system  Herat (NA)  Artificial Intelligence      10166.0
747         Caddie Health  Herat (NA)  Artificial Intelligence      10000.0
4340               Utiliz  Herat (NA)  Artificial Intelligence      10000.0

[315 rows x 4 columns]

In [14]:
"""Prepare raw data"""
df = pd.read_csv("/Users/robertpraas/CEPS-DST Dropbox/Robert Praas/cb_sep_25/funding_rounds.2026-01-07.53a0c76a.csv")
df["announced_on"] = pd.to_datetime(df["announced_on"])
df['year'] = df["announced_on"].dt.year


# """Location"""
# df = add_location_info(df)

# #find ipo and exit info
# orgs = pd.read_csv('organizations.2026-01-07.b425a1ff.csv',usecols=['identifier.permalink', 'ipo_status','exited_on.value'])

# df = df.merge(
#     orgs[['identifier.permalink', 'ipo_status','exited_on.value']],
#     left_on='funded_organization_identifier.permalink',
#     right_on='identifier.permalink',
#     how='left'
# )

/var/folders/kc/qz_hzm7s5dz81pxbkb0txsn00000gn/T/ipykernel_27420/1320993399.py:2: DtypeWarning: Columns (37,38,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/robertpraas/CEPS-DST Dropbox/Robert Praas/cb_sep_25/funding_rounds.2026-01-07.53a0c76a.csv")

In [16]:
df.columns

Index(['identifier.entity_def_id', 'identifier.uuid', 'identifier.permalink',
       'identifier.value', 'identifier.image_id', 'announced_on',
       'closed_on.value', 'closed_on.precision', 'created_at',
       'funded_organization_categories.entity_def_id',
       'funded_organization_categories.uuid',
       'funded_organization_categories.permalink',
       'funded_organization_categories.value',
       'funded_organization_categories.image_id',
       'funded_organization_description', 'funded_organization_funding_stage',
       'funded_organization_funding_total.value',
       'funded_organization_funding_total.currency',
       'funded_organization_funding_total.value_usd',
       'funded_organization_identifier.entity_def_id',
       'funded_organization_identifier.uuid',
       'funded_organization_identifier.permalink',
       'funded_organization_identifier.value',
       'funded_organization_identifier.image_id',
       'funded_organization_location.entity_def_id',
       'funded_organization_location.uuid',
       'funded_organization_location.permalink',
       'funded_organization_location.value',
       'funded_organization_location.image_id',
       'funded_organization_revenue_range', 'investment_stage',
       'investment_type', 'investor_identifiers.entity_def_id',
       'investor_identifiers.uuid', 'investor_identifiers.permalink',
       'investor_identifiers.value', 'investor_identifiers.image_id',
       'is_equity', 'lead_investor_identifiers.entity_def_id',
       'lead_investor_identifiers.uuid', 'lead_investor_identifiers.permalink',
       'lead_investor_identifiers.value', 'lead_investor_identifiers.image_id',
       'money_raised.value', 'money_raised.currency', 'money_raised.value_usd',
       'name', 'num_investors', 'num_partners', 'post_money_valuation.value',
       'post_money_valuation.currency', 'post_money_valuation.value_usd',
       'pre_money_valuation.value', 'pre_money_valuation.currency',
       'pre_money_valuation.value_usd', 'rank', 'rank_funding_round',
       'short_description', 'target_money_raised.value',
       'target_money_raised.currency', 'target_money_raised.value_usd',
       'updated_at', 'funded_organization_diversity_spotlights.entity_def_id',
       'funded_organization_diversity_spotlights.uuid',
       'funded_organization_diversity_spotlights.permalink',
       'funded_organization_diversity_spotlights.value',
       'funded_organization_diversity_spotlights.image_id', 'year'],
      dtype='object')

In [ ]:
Lovable

In [25]:
for i in test[test.geo=='Herat (NA)'].sort_values(by='count',ascending=0).head(10).org.to_list():

    print(df[df['funded_organization_identifier.value']==i]['funded_organization_location.value'])

1         Dover,Delaware,United States,North America
3548      Dover,Delaware,United States,North America
49431     Dover,Delaware,United States,North America
123721    Dover,Delaware,United States,North America
Name: funded_organization_location.value, dtype: object
2163    Bromont,Quebec,Canada,North America
Name: funded_organization_location.value, dtype: object
102       Freiburg Im Breisgau,Baden-Wurttemberg,Germany...
2749      Freiburg Im Breisgau,Baden-Wurttemberg,Germany...
104106    Freiburg Im Breisgau,Baden-Wurttemberg,Germany...
Name: funded_organization_location.value, dtype: object
6915      Donostia-san Sebastián,Pais Vasco,Spain,Europe
95440     Donostia-san Sebastián,Pais Vasco,Spain,Europe
241765    Donostia-san Sebastián,Pais Vasco,Spain,Europe
368030    Donostia-san Sebastián,Pais Vasco,Spain,Europe
380936    Donostia-san Sebastián,Pais Vasco,Spain,Europe
436400    Donostia-san Sebastián,Pais Vasco,Spain,Europe
511580    Donostia-san Sebastián,Pais Vasco,Spain,Europe
538929    Donostia-san Sebastián,Pais Vasco,Spain,Europe
566487    Donostia-san Sebastián,Pais Vasco,Spain,Europe
574830    Donostia-san Sebastián,Pais Vasco,Spain,Europe
Name: funded_organization_location.value, dtype: object
30303     Barongarook,Victoria,Australia,Oceania
346936    Barongarook,Victoria,Australia,Oceania
436315    Barongarook,Victoria,Australia,Oceania
507409    Barongarook,Victoria,Australia,Oceania
Name: funded_organization_location.value, dtype: object
2454      Cambridge,Cambridgeshire,United Kingdom,Europe
261737    Cambridge,Cambridgeshire,United Kingdom,Europe
Name: funded_organization_location.value, dtype: object
36344     Cambridge,Cambridgeshire,United Kingdom,Europe
234331    Cambridge,Cambridgeshire,United Kingdom,Europe
266587    Cambridge,Cambridgeshire,United Kingdom,Europe
396979    Cambridge,Cambridgeshire,United Kingdom,Europe
467118    Cambridge,Cambridgeshire,United Kingdom,Europe
539353    Cambridge,Cambridgeshire,United Kingdom,Europe
682855    Cambridge,Cambridgeshire,United Kingdom,Europe
Name: funded_organization_location.value, dtype: object
8099      Coimbra,Coimbra,Portugal,Europe
214310    Coimbra,Coimbra,Portugal,Europe
215818    Coimbra,Coimbra,Portugal,Europe
243862    Coimbra,Coimbra,Portugal,Europe
253693    Coimbra,Coimbra,Portugal,Europe
256735    Coimbra,Coimbra,Portugal,Europe
435512    Coimbra,Coimbra,Portugal,Europe
598833    Coimbra,Coimbra,Portugal,Europe
640451    Coimbra,Coimbra,Portugal,Europe
Name: funded_organization_location.value, dtype: object
832       Santa Barbara,California,United States,North A...
28494      Los Altos,California,United States,North America
250118     Los Altos,California,United States,North America
255170    Santa Barbara,California,United States,North A...
263583    Santa Barbara,California,United States,North A...
337148    Santa Barbara,California,United States,North A...
353069    Santa Barbara,California,United States,North A...
600813    Santa Barbara,California,United States,North A...
649553    Santa Barbara,California,United States,North A...
Name: funded_organization_location.value, dtype: object
2301      Oxford,Oxfordshire,United Kingdom,Europe
5783      Oxford,Oxfordshire,United Kingdom,Europe
372669    Oxford,Oxfordshire,United Kingdom,Europe
409396    Oxford,Oxfordshire,United Kingdom,Europe
413723    Oxford,Oxfordshire,United Kingdom,Europe
688655    Oxford,Oxfordshire,United Kingdom,Europe
696460    Oxford,Oxfordshire,United Kingdom,Europe
Name: funded_organization_location.value, dtype: object

In [ ]:
df[df['funded_organization_identifier.value']=='Lovable']['funded_organization_location.value']